
### Generated by PseudoScript 0.0.1 ###


### Imports ###
map = require './map'

# Abstracts #
Universe = map.abstracts.Universe
Noun = map.abstracts.Noun

# Concretes #
Room = map.concretes[0]
Light = map.concretes[1]

rooms = []
lights = []



### Code ###

# So you think you're god...
universe = new Universe()

# let there be a room
rooms.push new Room()
universe.add rooms[0]

# create another room called 'bedroom'
rooms.push new Room('bedroom')
universe.add rooms[1]

# add a light to the room
lights.push new Light()
rooms[1].add lights[0]

# how many lights in room?
console.log rooms

