
### Generated by PseudoScript 0.0.1 ###


### Imports ###
map = require './map'

# Abstracts #
Universe = map.abstracts.Universe
Noun = map.abstracts.Noun

# Concretes #
Room = map.concretes[0]
Light = map.concretes[1]



### Code ###

# So you think you're god...
universe = new Universe()

# let there be a room
room_0 = new Room()
universe.add room_0

# create another room called 'bedroom'
room_1 = new Room('bedroom')
universe.add room_1

# add a light to the room
light_0 = new Light()
room_1.add light_0

