// Generated by CoffeeScript 1.10.0

/* UTIL: RUN TIME */

(function() {
  var Promise, Util,
    slice = [].slice;

  Promise = require("promise");

  Util = (function() {
    function Util() {}

    Util.random = function(options) {
      return Math.floor(options.min + Math.random() * options.max);
    };

    Util.error = function(err) {
      return console.error(err);
    };

    Util.log = function(string) {
      return new Promise(function(resolve, reject) {
        console.log(string);
        return resolve();
      });
    };

    Util.math = {
      multiply: function() {
        var operands;
        operands = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return new Promise(function(resolve, reject) {
          return resolve(operands.reduce(function(prev, curr) {
            return prev * curr;
          }));
        });
      },
      divide: function(operands) {
        return new Promise(function(resolve, reject) {
          return resolve(operands.reduce(function(prev, curr) {
            return prev / curr;
          }));
        });
      },
      add: function(operands) {
        return new Promise(function(resolve, reject) {
          return resolve(operands.reduce(function(prev, curr) {
            return prev + curr;
          }));
        });
      },
      subtract: function(operands) {
        return new Promise(function(resolve, reject) {
          return resolve(operands.reduce(function(prev, curr) {
            return prev - curr;
          }));
        });
      }
    };

    return Util;

  })();

  module.exports = Util;

}).call(this);
