// Generated by CoffeeScript 1.10.0
(function() {
  var Light;

  Light = (function() {
    function Light() {}

    Light.properties = {
      'on': 'boolean',
      'color': 'string',
      'brightness': 'number'
    };

    return Light;

  })();

  console.log(Light);

  module.exports = {
    Light: Light
  };

}).call(this);
