// Generated by CoffeeScript 1.10.0
(function() {
  var Home, Module,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Module = require("./module");

  Home = (function(superClass) {
    extend(Home, superClass);

    Home.self = 'Home';

    Home.lexical = {
      base: 'home',
      plural: 'homes'
    };

    Home.members = [];

    Home.properties = {};

    function Home() {
      Home.__super__.constructor.call(this);
    }

    return Home;

  })(Module);

  module.exports = Home;

}).call(this);
