// Generated by CoffeeScript 1.10.0
var Find, Module;

Find = require("./../core/find");

Module = (function() {
  function Module() {}

  Module.index = 0;

  Module.members = [];

  Module.children = [];

  Module.parent = null;

  Module.add = function(ref, parent) {
    Module.members.push({
      module: this.self,
      ref: ref
    });
    this.members.push(ref);
    return this.index++;
  };

  Module.select = function(ref) {
    var i, len, member, ref1;
    ref1 = this.members;
    for (i = 0, len = ref1.length; i < len; i++) {
      member = ref1[i];
      if (ref === member.ref) {
        return member;
      }
    }
  };

  return Module;

})();

module.exports = Module;
