// Generated by CoffeeScript 1.10.0
(function() {
  var Home, Light, Room;

  Light = require("./light");

  Room = require("./room");

  Home = require("./home");

  module.exports = [Light, Room, Home];

}).call(this);
