// Generated by CoffeeScript 1.10.0
(function() {
  var Home, Light, Room, Shaker;

  Light = require("./light");

  Room = require("./room");

  Home = require("./home");

  Shaker = require("./shaker");

  module.exports = [Light, Room, Home, Shaker];

}).call(this);
