// Generated by CoffeeScript 1.10.0
(function() {
  var Module;

  Module = (function() {
    function Module() {}

    Module.members = [];

    return Module;

  })();

  module.exports = Module;

}).call(this);
