// Generated by CoffeeScript 1.10.0
(function() {
  var Room;

  Room = (function() {
    function Room() {}

    Room.properties = {
      'dark': {
        type: 'boolean',
        set: false
      },
      'temperature': {
        type: 'number',
        set: false
      },
      'threshold': {
        type: 'number',
        set: true
      }
    };

    Room.lexical = {
      base: 'room'
    };

    return Room;

  })();

  module.exports = Room;

}).call(this);
