// Generated by CoffeeScript 1.10.0
(function() {
  var Adverb, Time, Util, dict, str,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Adverb = require("./adverb");

  Util = require("../../util");

  dict = require("../../dictionaries/dictionary").adverbs;

  Time = (function(superClass) {
    extend(Time, superClass);

    function Time() {
      return Time.__super__.constructor.apply(this, arguments);
    }

    Time.types = dict.time.types;

    Time.units = dict.time.units;

    Time.getPrepositions = function() {
      var i, k, len, preposition, prepositions, ref, ref1, v;
      prepositions = [];
      ref = this.types;
      for (k in ref) {
        v = ref[k];
        ref1 = v.prepositions;
        for (i = 0, len = ref1.length; i < len; i++) {
          preposition = ref1[i];
          prepositions.push(preposition);
        }
      }
      return prepositions;
    };

    Time.getType = function(preposition) {
      var i, k, len, p, ref, ref1, v;
      ref = this.types;
      for (k in ref) {
        v = ref[k];
        ref1 = v.prepositions;
        for (i = 0, len = ref1.length; i < len; i++) {
          p = ref1[i];
          if (preposition === p) {
            return k;
          }
        }
      }
    };

    Time.getUnits = function() {
      var i, k, len, ref, unit, units, v;
      units = [];
      ref = this.units;
      for (k in ref) {
        v = ref[k];
        for (i = 0, len = v.length; i < len; i++) {
          unit = v[i];
          units.push(unit);
        }
      }
      return units;
    };

    Time.getUnit = function(expression) {
      var i, k, len, pattern, ref, unit, v;
      ref = this.units;
      for (k in ref) {
        v = ref[k];
        for (i = 0, len = v.length; i < len; i++) {
          unit = v[i];
          pattern = Util.regex.bound(unit);
          if (expression.match(pattern) != null) {
            return k;
          }
        }
      }
    };

    Time.getTime = function(text) {
      var expressions, i, len, pattern, result, results, time, unit, units, value;
      units = Util.regex.group(this.getUnits());
      pattern = new RegExp("\\d+\\s+?\\b" + units + "\\b", "g");
      results = [];
      while (true) {
        result = pattern.exec(text);
        if (result != null) {
          results.push(result[0]);
        } else {
          break;
        }
      }
      expressions = [];
      for (i = 0, len = results.length; i < len; i++) {
        result = results[i];
        pattern = /\b\d+\b/g;
        value = pattern.exec(result)[0];
        pattern = new RegExp("(\\b)|(\\d+))" + units + "(\\b)|(\\d+)", "g");
        unit = this.getUnit(pattern.exec(result)[0]);
        time = {};
        time[unit] = value;
        expressions.push(time);
      }
      console.log(expressions);
      return this.time2ms(time);
    };

    Time.test = function(text) {
      var match, pattern, preposition, time, type;
      pattern = Util.regex.group(this.getPrepositions());
      pattern = Util.regex.bound(pattern);
      match = text.match(pattern);
      if (match != null) {
        preposition = match[0];
      }
      type = this.getType(preposition);
      time = this.getTime(text);
      return {
        type: type,
        time: time
      };
    };

    Time.time2ms = function(time) {
      var milliseconds;
      milliseconds = 0;
      if (time.days != null) {
        milliseconds += time.days * 1000 * 60 * 60 * 24;
      }
      if (time.hours != null) {
        milliseconds += time.hours * 1000 * 60 * 60;
      }
      if (time.minutes != null) {
        milliseconds += time.minutes * 1000 * 60;
      }
      if (time.seconds != null) {
        milliseconds += time.seconds * 1000;
      }
      if (time.milliseconds != null) {
        milliseconds += time.milliseconds;
      }
      return milliseconds;
    };

    return Time;

  })(Adverb);

  str = "Every 2m45s";

  console.log(Time.test(str.toLowerCase()));

  module.exports = Time;

}).call(this);
