// Generated by CoffeeScript 1.10.0

/* Generated by PseudoScript 0.0.1 */


/* Imports */

(function() {
  var Light, Noun, Room, Universe, light_0, map, room_0, room_1, universe;

  map = require('./map');

  Universe = map.abstracts.Universe;

  Noun = map.abstracts.Noun;

  Room = map.concretes[0];

  Light = map.concretes[1];


  /* Code */

  universe = new Universe();

  room_0 = new Room();

  universe.add(room_0);

  room_1 = new Room('bedroom');

  universe.add(room_1);

  light_0 = new Light();

  room_1.add(light_0);

}).call(this);
