// Generated by CoffeeScript 1.10.0

/* VERB: GET */

(function() {
  var Find, Get, Module, Scope, Verb, modules,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  modules = require("../../modules/modules");

  Module = require("../../modules/module");

  Scope = require("./../scope");

  Find = require("./../../core/find");

  Verb = require("./verb");

  Get = (function(superClass) {
    extend(Get, superClass);

    function Get() {
      return Get.__super__.constructor.apply(this, arguments);
    }

    Get.lexical = {
      base: 'get',
      synonyms: ['get']
    };

    Get.getObject = function(segment) {

      /* FIND OBJECT AND REFERENCE */
      var err, error, error1, i, len, match, module, object, ref;
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        match = segment.match(module.lexical.base);
        if (match != null) {
          object = module.self;
          break;
        }
      }
      ref = Find.reference(segment);
      if (object == null) {
        if (ref != null) {
          try {
            object = Module.fetch(ref).module;
          } catch (error) {
            err = error;
            console.error("Error! '" + ref + "' not found.");
          }
        } else {
          object = Scope.current.object;
          ref = Scope.current.ref;
        }
      } else {
        if (ref != null) {
          try {
            object = Module.fetch(ref).module;
          } catch (error1) {
            err = error1;
            console.error("Error! '" + ref + "' not found.");
          }
        } else {
          ref = Scope.modules[object].ref;
        }
      }
      return [object, ref];
    };

    Get.getProperty = function(segment, object) {

      /* FIND PROPERTY */
      var key, match, module, property, ref1, value;
      module = Find.module(object);
      ref1 = module.properties;
      for (key in ref1) {
        value = ref1[key];
        match = segment.match(key);
        if (match != null) {
          property = key;
        }
      }
      if (property == null) {
        property = Scope.modules[object].property;
      }
      return property;
    };

    Get.parse = function(segment) {
      var object, property, ref, ref1;
      ref1 = this.getObject(segment), object = ref1[0], ref = ref1[1];
      property = this.getProperty(segment, object);
      Scope.current = {
        object: object,
        ref: ref,
        property: property
      };
      Scope.modules[object] = {
        ref: ref,
        property: property
      };
      return {
        object: object,
        ref: ref,
        property: property
      };
    };

    Get.test = function(text) {
      var match, pattern, segments, split;
      pattern = /\bget .*( to)? \b(.*)\b/g;
      match = text.match(pattern);
      if (match != null) {
        split = this.split(match[0]);
        segments = split.map((function(_this) {
          return function(segment) {
            return _this.parse(segment);
          };
        })(this));
        return {
          type: 'verb',
          verb: 'get',
          operations: segments
        };
      }
    };

    return Get;

  })(Verb);

  module.exports = Get;

}).call(this);
