// Generated by CoffeeScript 1.10.0
(function() {
  var Verb;

  Verb = (function() {
    function Verb() {}

    Verb.split = function(text) {
      var parts, pattern;
      pattern = /\s+and\s+|,|\s+&\s+/g;
      parts = text.split(pattern);
      parts = parts.map(function(part) {
        return part.trim();
      });
      return parts.filter(function(part) {
        return part !== '';
      });
    };

    return Verb;

  })();

  module.exports = Verb;

}).call(this);
