// Generated by CoffeeScript 1.10.0
(function() {
  var Add, Get, Log, Set;

  Add = require("./add");

  Set = require("./set");

  Get = require("./get");

  Log = require("./log");

  module.exports = [Add, Set, Get, Log];

}).call(this);
