// Generated by CoffeeScript 1.10.0
(function() {
  var dictionary;

  dictionary = {
    verbs: {
      'turn on': {
        property: "on",
        value: true,
        type: 'set'
      },
      'set': {
        property: null,
        value: null,
        type: 'set'
      },
      'create': {
        type: 'create'
      }
    }
  };

  module.exports = dictionary;

}).call(this);
