### generated by pseudoscript 0.1 ###

# Adding new Home 'home_0'
new Home('home_0')

# Adding new Room 'living room' to Home 'home_0'
new Room('living room', 'home_0')

# Adding new Light 'ceiling light' to Room 'living room'
new Light('ceiling light', 'living room')

# Setting 'color' of 'ceiling light' to 'blue'
Light.select('ceiling light').set('color', 'blue')

# Setting interval to 10 seconds
setInterval () ->

  # Setting 'color' of 'ceiling light' to 'red'
  Light.select('ceiling light').set('color', 'red')

  # Setting timeout to 5 seconds
  setTimeout () ->

    # Setting 'color' of 'ceiling light' to 'blue'
    Light.select('ceiling light').set('color', 'blue')

  , (5*1000)

, (10*1000)

# Setting timeout to 5430 seconds
setTimeout () ->

  # Setting 'temperature' of 'living room' to '20'
  Room.select('living room').set('temperature', '20')

, (5430*1000)