// Generated by CoffeeScript 1.10.0

/* generated by pseudoscript 0.1 */

(function() {
  var Globals, Light, Room, Shaker, Util;

  Util = require('../src/core/util');

  Globals = require('../src/core/runtime/globals');

  Light = require('../src/modules/light');

  Room = require('../src/modules/room');

  Shaker = require('../src/modules/shaker');

  new Light('Hue 1');

  new Shaker('shaker 1');

  Shaker.on('shaker 1', 'shake', function() {
    return Light.set('Hue 1', {
      brightness: 1
    })["catch"](function(err) {
      return Util.error(err);
    });
  }).then(function() {
    return "done";
  });

}).call(this);
