// Generated by CoffeeScript 1.10.0
(function() {
  var dictionary;

  dictionary = {
    verbs: {
      '(turn on)|(turn .*? on)': {
        property: "on",
        value: true,
        type: 'set'
      },
      '(turn off)|(turn .*? off)': {
        property: "on",
        value: false,
        type: 'set'
      },
      'set .*? to': {
        type: 'set'
      },
      'increase .*? to': {
        type: 'set'
      },
      'decrease .*? to': {
        type: 'set'
      },
      'turn .*? up to': {
        type: 'set'
      },
      'turn .*? down to': {
        type: 'set'
      },
      'blink': {
        type: 'do',
        action: 'blink',
        value: 3
      },
      '(create)|(add)|(connect)': {
        type: 'create'
      },
      '(show)|(show me)|(display)': {
        type: 'log'
      },
      'increase .*? by': {
        type: 'increase'
      },
      'turn .*? up by': {
        type: 'increase'
      },
      'decrease .*? by': {
        type: 'decrease'
      },
      'turn .*? down by': {
        type: 'decrease'
      }
    },
    adverbs: {
      '^(in)|(after) \\d+': {
        type: 'delay'
      }
    },
    events: {
      'when .*? button': {
        event: 'button'
      }
    },
    units: {
      milliseconds: {
        pattern: /\d+\s+(milliseconds)|(ms)\b/g
      },
      seconds: {
        pattern: /\d+\s+(seconds)|(sec)|(s)\b/g
      },
      minutes: {
        pattern: /\d+\s+(minutes)|(min)|(m)\b/g
      },
      hours: {
        pattern: /\d+\s+(hours)|(h)\b/g
      },
      days: {
        pattern: /\d+\s+(days)|(d)\b/g
      }
    }
  };

  module.exports = dictionary;

}).call(this);
