// Generated by CoffeeScript 1.10.0
(function() {
  var Photon, Promise, Spark, fs;

  Spark = require("spark");

  Promise = require("promise");

  fs = require("fs");

  Photon = (function() {
    Photon.photon = null;

    function Photon() {
      Photon.photon = null;
      this.ref = 'fisk';
    }

    Photon.prototype.connect = function() {
      return new Promise(function(resolve, reject) {
        var credentials;
        credentials = fs.readFileSync("credentials.json", "utf8");
        credentials = JSON.parse(credentials);
        Spark.login(credentials);
        return Spark.on('login', function() {
          var devices;
          devices = Spark.listDevices();
          return devices.then(function(devices) {
            Photon.photon = devices[0];
            Photon.photon.onEvent('dark', function(data) {
              return console.log("Incoming event! Dark: " + JSON.stringify(data));
            });
            return resolve("connected");
          }, function(err) {
            return reject(err);
          });
        });
      });
    };

    Photon.prototype.set = function(property, value) {
      return new Promise(function(resolve, reject) {
        value = value.toString();
        if (property === 'color') {
          Photon.photon.callFunction('setColor', value, function(err, data) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data);
            }
          });
        }
        if (property === 'brightness') {
          Photon.photon.callFunction('setB', value, function(err, data) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data);
            }
          });
        }
        if (property === 'on') {
          return Photon.photon.callFunction('flip', value, function(err, data) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data);
            }
          });
        }
      });
    };

    Photon.prototype["do"] = function(action, value) {
      return new Promise(function(resolve, reject) {
        value = value.toString();
        if (action === 'blink') {
          return Photon.photon.callFunction('blink', value, function(err, data) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data);
            }
          });
        }
      });
    };

    return Photon;

  })();

  module.exports = Photon;

}).call(this);
