// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, Test, run, test;

  Promise = require("promise");

  run = function() {
    return new Promise(function(resolve, reject) {
      return setTimeout(function() {
        return resolve("done");
      }, 1000);
    });
  };

  Test = (function() {
    function Test() {
      new Promise(function(resolve, reject) {
        return setTimeout(function() {
          return resolve("test");
        }, 1000);
      });
    }

    return Test;

  })();

  test = new Test();

  test.then(function(result) {
    return console.log(result);
  });


  /*
  run()
  
  .then (result) ->
    console.log result
    run()
  
  .then (result) ->
    console.log result
    run()
   */

}).call(this);
