// Generated by CoffeeScript 1.10.0
(function() {
  var Photon, Promise, photon;

  Promise = require("promise");

  Photon = require("./js/photon");

  photon = new Photon();

  photon.connect().then(function() {
    setTimeout(function() {
      return photon.set('color', 'red');
    }, 1000);
    return setTimeout(function() {
      return photon.set('color', 'yellow');
    }, 2000);
  });

}).call(this);
