// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, Photon, Programmer, argv, code, command, dictionary, map, parser, photon, programmer, script;

  dictionary = require("./dictionary");

  map = require("./map");

  argv = require("yargs").argv;

  Parser = require("./parser");

  Programmer = require("./programmer");

  Photon = require("./photon");

  command = "add a light called 'ceiling light', set the brightness to 45 and increase the timer by 10 minutes";

  if (argv._[0] != null) {
    command = argv._[0];
  }

  photon = new Photon();

  photon.connect().then((function(result) {
    console.log("connected");
    return photon.set('color', 'white');

    /*photon.onEvent 'dark', (data) ->
      console.log "DARK"
      console.log data
     */
  }, function(err) {
    return console.error(err);
  }));

  setInterval(function() {
    return null;
  }, 5000);

  return;

  parser = new Parser(dictionary, map);

  programmer = new Programmer(map);

  script = parser.parse(command);

  code = programmer.process(script);

  console.log(programmer.wrap(code));

}).call(this);
