#! /usr/bin/env node

// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, Programmer, argv, code, command, dictionary, map, parser, programmer, script;

  dictionary = require("./dictionary");

  map = require("./map");

  argv = require("yargs").argv;

  Parser = require("./parser");

  Programmer = require("./programmer");

  command = "add a light called 'ceiling light', set the brightness to 45 and increase the timer by 10 minutes";

  if (argv._[0] != null) {
    command = argv._[0];
  }

  parser = new Parser(dictionary, map);

  programmer = new Programmer(map);

  script = parser.parse(command);

  code = programmer.process(script);

  console.log(programmer.wrap(code));

}).call(this);
