// Generated by CoffeeScript 1.10.0
(function() {
  var Light, Photon, Room, map, photon;

  map = require('./map');

  Room = map.Room;

  Light = map.Light;

  Photon = require('./photon');

  photon = new Photon();

  console.log('# Running script #');

  photon.connect().then(function() {
    console.log('Connected!');
    new Light('test', photon);
    Light.get('test').set('brightness', 100);
    setTimeout(function() {
      return Light.get('test').set('color', 'yellow');
    }, 1000);
    setInterval(function() {
      return Light.get('test').set('color', 'random');
    }, 3000);
    return photon.on('button', function() {
      return Light.get('test').set('brightness', 10);
    });
  });

}).call(this);
