// Generated by CoffeeScript 1.10.0
(function() {
  var Light, Photon, Room, map, photon;

  map = require('./map');

  Room = map.Room;

  Light = map.Light;

  Photon = require('./photon');

  photon = new Photon();

  console.log('# Running script #');

  photon.connect().then(function() {
    console.log('Connected!');
    photon.on('button', function() {
      return console.log('button pushed');
    });
    new Light('test', photon);
    Light.get('test')["do"]('blink', 3);
    setTimeout(function() {
      return Light.get('test').set('color', 'red');
    }, 2000);
    return setTimeout(function() {
      Light.get('test').set('color', 'blue');
      return Light.get('test').set('color', 'yellow');
    }, 3000);
  });

}).call(this);
