// Generated by CoffeeScript 1.10.0
(function() {
  var Light, Photon, Room, map, photon;

  map = require('./map');

  Room = map.Room;

  Light = map.Light;

  Photon = require('./photon');

  photon = new Photon();

  console.log('# Running script #');

  photon.connect().then(function() {
    new Light('undefined', photon);
    return Light.get('undefined').set('on', false);
  }).then(function() {
    return console.log('# End of script #');
  });

}).call(this);
