// Generated by CoffeeScript 1.10.0
(function() {
  var Photon, map, photon;

  map = require('./map');

  Photon = require('./photon');

  photon = new Photon();

  photon.connect().then(function() {
    var Light, Room;
    Room = map.Room;
    Light = map.Light;
    new Light('test', photon);
    Light.get('test').set('color', 'red');
    return Light.get('test').set('brightness', 100);
  });

}).call(this);
