// Generated by CoffeeScript 1.10.0
(function() {
  var Light, Room, map;

  map = require('./map');

  Room = map.Room;

  Light = map.Light;

  new Light('ceiling light');

  Light.get('ceiling light').set('brightness', 45);

  Light.get('ceiling light').inc('timer', 10);

  console.log(Light);

}).call(this);
