// Generated by CoffeeScript 1.10.0
(function() {
  var dictionary;

  dictionary = {
    verbs: {
      '(turn on)|(turn .*? on)': {
        property: "on",
        value: true,
        type: 'set'
      },
      '(turn off)|(turn .*? off)': {
        property: "on",
        value: false,
        type: 'set'
      },
      'set .*? to': {
        type: 'set'
      },
      'increase .*? to': {
        type: 'set'
      },
      'decrease .*? to': {
        type: 'set'
      },
      'turn .*? up to': {
        type: 'set'
      },
      'turn .*? down to': {
        type: 'set'
      },
      'create': {
        type: 'create'
      },
      'increase .*? by': {
        type: 'increase'
      },
      'turn .*? up by': {
        type: 'increase'
      },
      'decrease .*? by': {
        type: 'decrease'
      },
      'turn .*? down by': {
        type: 'decrease'
      },
      'is .*? ?': {
        type: 'question'
      },
      'what .*? \?': {
        type: 'question'
      },
      'if .*? (then)|(,)': {
        type: 'conditional'
      }
    },
    adverbs: {
      'in \d+ s': {
        type: 'delay'
      }
    },
    timeUnits: {
      milliseconds: {
        pattern: /(milliseconds)|(ms) /,
        process: function(time) {
          return time;
        }
      },
      seconds: {
        pattern: /(seconds)|(s) /,
        process: function(time) {
          return time * 1000;
        }
      },
      minutes: {
        pattern: /(minutes)|(min) /,
        process: function(time) {
          return time * 1000 * 60;
        }
      },
      hours: {
        pattern: /(hours)|(h) /,
        process: function(time) {
          return time * 1000 * 60 * 60;
        }
      },
      days: {
        pattern: /days /,
        process: function(time) {
          return time * 1000 * 60 * 60 * 24;
        }
      }
    }
  };

  module.exports = dictionary;

}).call(this);
