// Generated by CoffeeScript 1.10.0
(function() {
  var adverbs, i, j, k, keywords, len, len1, len2, prep, preps, ref, synonym, verb, verbs;

  verbs = require("./verbs/verbs");

  adverbs = require("./adverbs/adverbs");

  keywords = [];

  for (i = 0, len = verbs.length; i < len; i++) {
    verb = verbs[i];
    ref = verb.lexical.synonyms;
    for (j = 0, len1 = ref.length; j < len1; j++) {
      synonym = ref[j];
      keywords.push(synonym);
    }
  }

  preps = ["after", "in", "wait", "in", "every"];

  for (k = 0, len2 = preps.length; k < len2; k++) {
    prep = preps[k];
    keywords.push(prep);
  }

  module.exports = {
    adverbs: adverbs,
    verbs: verbs,
    keywords: keywords
  };

}).call(this);
