// Generated by CoffeeScript 1.10.0
(function() {
  var Add, Adverb, Set, dict;

  dict = require("../dictionaries/base");

  Adverb = require("./adverb");

  Set = require("./verbs/set");

  Add = require("./verbs/add");

  module.exports = {
    adverb: new Adverb(dict),
    verbs: [Add, Set]
  };

}).call(this);
