// Generated by CoffeeScript 1.10.0
(function() {
  var Scope, modules;

  modules = require("../modules/modules");

  Scope = (function() {
    function Scope() {}

    Scope.modules = [];

    Scope.current = {};

    Scope.type = null;

    Scope.subtype = null;

    Scope.variables = [];

    Scope.getByRef = function(ref) {
      var k, ref1, v;
      ref1 = Scope.modules;
      for (k in ref1) {
        v = ref1[k];
        if (ref === v.ref) {
          return k;
        }
      }
    };

    return Scope;

  })();

  module.exports = Scope;

}).call(this);
