// Generated by CoffeeScript 1.10.0
(function() {
  var Scope, modules;

  modules = require("../modules/modules");

  Scope = (function() {
    function Scope() {}

    Scope.modules = [];

    Scope.current = {};

    Scope.type = null;

    Scope.subtype = null;

    return Scope;

  })();

  module.exports = Scope;

}).call(this);
