// Generated by CoffeeScript 1.10.0
(function() {
  var Set;

  Set = (function() {
    function Set(dict) {
      this.dict = dict;
    }

    Set.prototype.find = function(text) {
      var def, entry, match, ref;
      ref = this.dict.adverbs;
      for (entry in ref) {
        def = ref[entry];
        match = text.match(def.pattern);
        if (match != null) {
          return entry;
        }
      }
    };

    Set.prototype.test = function(text) {
      var match, pattern;
      pattern = /\bset .*( to)? \b(.*)\b/g;
      match = text.match(pattern);
      if (match != null) {
        return match;
      }
    };

    return Set;

  })();

  module.exports = Set;

}).call(this);
