// Generated by CoffeeScript 1.10.0
(function() {
  light.on = true;

  light.timer = 30;

  light.on = true;

  light.brightness = 50;

  light.brightness += 50;

  light.on = false;

  light.timer = 20;

  light.on = true;

  light.on = 45;

  light.brightness = 40;

}).call(this);
