// Generated by CoffeeScript 1.10.0
(function() {
  var dictionary;

  dictionary = {
    adverbs: {
      time: {
        units: {
          milliseconds: ["milisecond(s)?", "ms"],
          seconds: ["second(s)?", "sec(s)?", "s"],
          minutes: ["minute(s)?", "min(s)?", "m"],
          hours: ["hour(s)?", "h"],
          days: ["day(s)?", "d"]
        },
        types: {
          delay: {
            prepositions: ["in", "after", "wait"]
          },
          interval: {
            prepositions: ["every"]
          }
        }
      }
    }
  };

  module.exports = dictionary;

}).call(this);
