// Generated by CoffeeScript 1.10.0
(function() {
  var Find, modules;

  modules = require("../modules/modules");

  Find = (function() {
    function Find() {}

    Find.object = function(text) {
      var i, len, match, module;
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        match = text.match(module.lexical.base);
        if (match != null) {
          return module.self;
        }
      }
    };

    Find.objects = function(text) {
      var i, len, match, matches, module;
      matches = [];
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        match = text.match(module.lexical.base);
        if (match != null) {
          matches.push(module.self);
        }
      }
      return matches;
    };

    Find.module = function(object) {
      var i, len, match, module;
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        match = object.match(module.self);
        if (match != null) {
          return module;
        }
      }
    };

    Find.word = function(object) {
      var i, len, match, module;
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        match = object.match(module.self);
        if (match != null) {
          return module.lexical.base;
        }
      }
    };

    Find.getModuleByRef = function(ref) {
      var i, j, len, len1, member, module, ref1;
      for (i = 0, len = modules.length; i < len; i++) {
        module = modules[i];
        ref1 = module.members;
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          member = ref1[j];
          if (ref === member) {
            return module.self;
          }
        }
      }
    };

    Find.references = function(text) {
      var matches;
      matches = text.match(/'[^']*'/g);
      if (matches != null) {
        return matches.map(function(match) {
          return match.replace(/'/g, '');
        });
      }
    };

    Find.number = function(text) {
      var i, len, match, pattern, ref, refs;
      refs = this.references(text);
      if (refs != null) {
        for (i = 0, len = refs.length; i < len; i++) {
          ref = refs[i];
          text = text.replace("'" + ref + "'", '');
        }
      }
      pattern = /\b([0-9]+([.][0-9]*)*)\b/g;
      match = text.match(pattern);
      if (match != null) {
        return match[0];
      }
    };

    Find.boolean = function(text) {
      var match, pattern;
      pattern = /\b((true)|(false))\b/g;
      match = text.match(pattern);
      if (match != null) {
        return match[0];
      }
    };

    return Find;

  })();

  module.exports = Find;

}).call(this);
