// Generated by CoffeeScript 1.10.0
(function() {
  var Globals;

  Globals = (function() {
    function Globals() {}

    Globals.variables = {};

    Globals.set = function(object) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          var key, value;
          for (key in object) {
            value = object[key];
            if (key === 'set') {
              reject("Cannot name global variable 'set'");
            } else {
              _this[key] = value;
            }
          }
          return resolve(object);
        };
      })(this));
    };

    return Globals;

  })();

  module.exports = Globals;

}).call(this);
