// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, Parts, Scope, Util, error, log, modules, tools;

  tools = require("monky-tools");

  Parts = require("./../parts/parts");

  Scope = require("./../parts/scope");

  Util = require("./util");

  modules = require("./../modules/modules");

  log = tools.console.log;

  error = tools.console.error;

  Parser = (function() {
    function Parser() {}

    Parser.phrasify = function(line) {
      var i, index, indices, j, keywords, len, pattern, phrases, result;
      keywords = Util.regex.group(Parts.keywords);
      pattern = Util.regex.bound(keywords);
      indices = [];
      while (true) {
        result = pattern.exec(line);
        if (result != null) {
          indices.push(result.index);
        } else {
          break;
        }
      }
      indices.sort(function(a, b) {
        return a > b;
      });
      phrases = [];
      for (i = j = 0, len = indices.length; j < len; i = ++j) {
        index = indices[i];
        if (indices[i + 1] == null) {
          phrases.push(line.slice(index));
          break;
        } else {
          phrases.push(line.slice(index, indices[i + 1]));
        }
      }
      return phrases;
    };

    Parser.action = function(phrase, scope) {
      var j, key, len, list, match, module, ref, value;
      list = {};
      for (j = 0, len = modules.length; j < len; j++) {
        module = modules[j];
        list[module.self] = [];
        ref = module.actions;
        for (key in ref) {
          value = ref[key];
          list[module.self].push(key);
        }
      }
      for (key in list) {
        value = list[key];
        if (value.length === 0) {
          delete list[key];
        }
      }
      for (key in list) {
        value = list[key];
        match = phrase.match(value);
        if (match != null) {
          return {
            type: 'action',
            action: value,
            object: Scope.current.object,
            ref: Scope.current.ref
          };
        }
      }
    };

    Parser.parse = function(line) {
      var adverb, j, k, l, len, len1, len2, phrase, phrases, ref, ref1, result, segments, verb;
      segments = [];
      phrases = this.phrasify(line);
      for (j = 0, len = phrases.length; j < len; j++) {
        phrase = phrases[j];

        /* ADVERB */
        ref = Parts.adverbs;
        for (k = 0, len1 = ref.length; k < len1; k++) {
          adverb = ref[k];
          result = adverb.test(phrase);
          if (result != null) {
            segments.push(result);
          }
        }

        /* VERBS (GENERAL) */
        ref1 = Parts.verbs;
        for (l = 0, len2 = ref1.length; l < len2; l++) {
          verb = ref1[l];
          result = verb.test(phrase);
          if (result != null) {
            Scope.type = 'verb';
            Scope.subtype = verb.lexical.base;
            segments.push(result);
          }
        }

        /* VERBS (MODULE ACTIONS) */
        result = this.action(phrase);
        if (result != null) {
          segments.push(result);
        }
      }
      return segments;
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
