// Generated by CoffeeScript 1.10.0
(function() {
  var Util;

  Util = (function() {
    function Util() {}

    Util.regex = {
      group: function(expressions) {
        var pattern;
        pattern = expressions.map(function(expression) {
          return "(" + expression + ")";
        });
        return pattern = pattern.join("|");
      },
      enclose: function(expression) {
        return "(" + expression + ")";
      },
      bound: function(pattern) {
        return new RegExp("\\b(" + pattern + ")\\b", "g");
      }
    };

    Util.random = function(options) {
      return Math.floor(options.min + Math.random() * options.max);
    };

    return Util;

  })();

  module.exports = Util;

}).call(this);
