// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, Util;

  Promise = require("promise");

  Util = (function() {
    function Util() {}

    Util.regex = {
      groupAndBound: function(expressions) {
        var pattern, words;
        words = expressions.join("|");
        return pattern = new RegExp("\\b" + words + "\\b");
      },
      groupAndBoundGlobal: function(expressions) {
        var pattern, words;
        words = expressions.join("|");
        return pattern = new RegExp("\\b" + words + "\\b", "g");
      },
      group: function(expressions) {
        var pattern;
        pattern = expressions.map(function(expression) {
          return "(" + expression + ")";
        });
        return pattern = pattern.join("|");
      },
      enclose: function(expression) {
        return "(" + expression + ")";
      },
      bound: function(pattern) {
        return new RegExp("\\b(" + pattern + ")\\b", "g");
      }
    };

    Util.debug = function(string) {
      return console.log(string);
    };

    return Util;

  })();

  module.exports = Util;

}).call(this);
