// Generated by CoffeeScript 1.10.0

/* GENERATED BY PSEUDOSCRIPT 0.1 */

(function() {
  new Room('living room');

  new Light('living room');

  setTimeout(function() {
    return Light.select('living room').set('brightness', '20');
  }, 30 * 1000);

}).call(this);
