// Generated by CoffeeScript 1.10.0

/* generated by pseudoscript 0.1 */

(function() {
  new Home('home_0');

  new Room('living room', 'home_0');

  new Light('ceiling light', 'living room');

  Light.select('ceiling light').set('color', 'blue');

  setInterval(function() {
    Light.select('ceiling light').set('color', 'red');
    return setTimeout(function() {
      return Light.select('ceiling light').set('color', 'blue');
    }, 5 * 1000);
  }, 10 * 1000);

  setTimeout(function() {
    return Room.select('living room').set('temperature', '20');
  }, 5430 * 1000);

}).call(this);
