### generated by pseudoscript 0.1 ###

# Core modules
Util = require '../src/core/util'

# Custom modules
Light = require '../src/modules/light'
Room = require '../src/modules/room'

# Adding new Light 'Hue 1'
new Light 'Hue 1'

# Setting properties of 'Hue 1'
Light.select 'Hue 1'
.then -> Light.set
  hue: 30000
  brightness: 100
  saturation: 250

# Getting properties of 'Hue 1'
Light.select 'Hue 1'
.then -> Light.get ['hue', 'saturation']

# Logging
.then (response) ->
  console.log "#{response.ref} (#{response.object})"
  console.log "  #{key}: #{value}" for key, value of response.properties
