// Generated by CoffeeScript 1.10.0

/* generated by pseudoscript 0.1 */

(function() {
  var Light;

  Light = require("../src/modules/light");

  new Light('Hue 1');

  Light.select('Hue 1').then(function() {
    return Light.set({
      hue: Math.floor(Math.random() * 65000, {
        brightness: 200,
        transitionTime: 1
      })
    });
  });

}).call(this);
