### generated by pseudoscript 0.1 ###

# Core modules
Util = require '../src/core/util'

# Custom modules
Light = require '../src/modules/light'
Room = require '../src/modules/room'

# Adding new Light 'Hue 1'
new Light 'Hue 1'

# Setting interval to 2 seconds
setInterval () ->

  # Setting properties of 'Hue 1'
  Light.select 'Hue 1'
  .then -> Light.set {hue: Util.random(min: 0, max: 65535), transitionTime: 4, brightness: Util.random(min: 0, max: 254)}

, (2*1000)

# Adding new Light 'Hue 2'
new Light 'Hue 2'

# Setting properties of 'Hue 2'
Light.select 'Hue 2'
.then -> Light.set {saturation: 0, brightness: 250}

# Setting interval to 0.2 seconds
setInterval () ->

  # Setting properties of 'Hue 2'
  Light.select 'Hue 2'
  .then -> Light.set {brightness: 250, transitionTime: 0}

  # Setting timeout to 0.1 seconds
  setTimeout () ->

    # Setting properties of 'Hue 2'
    Light.select 'Hue 2'
    .then -> Light.set {brightness: 0, transitionTime: 0}

  , (0.1*1000)

, (0.2*1000)

