### generated by pseudoscript 0.1 ###

# Core modules
Util = require '../src/core/runtime/util'
Globals = require '../src/core/runtime/globals'

# Custom modules
Light = require '../src/modules/light'
Room = require '../src/modules/room'
Shaker = require '../src/modules/shaker'

# Add new Light 'Hue 1'
new Light 'Hue 1'

# Add new Shaker 'shaker 1'
new Shaker 'shaker 1'

# Performing action 'connect'
Shaker.do 'shaker 1', 'connect'

# On event 'start' for 'shaker 1'
Shaker.on 'shaker 1', 'start', () ->

  # Log strings
  Util.log string for string in ['fisk']
  # Catch errors
  .catch (err) -> Util.error err


