### generated by pseudoscript 0.1 ###

# Core modules
Util = require '../src/core/util'
Globals = require '../src/core/runtime/globals'

# Custom modules
Light = require '../src/modules/light'
Room = require '../src/modules/room'
Shaker = require '../src/modules/shaker'

# Add new Light 'Hue 1'
new Light 'Hue 1'

# Add new Shaker 'shaker 1'
new Shaker 'shaker 1'

# On event 'shake' for 'shaker 1'
Shaker.on 'shaker 1', 'shake', () ->

  # Set properties of 'Hue 1'
  Light.set 'Hue 1', 
    brightness: 1

  # Catch errors
  .catch (err) -> Util.error err

.then -> "done"



