// Generated by CoffeeScript 1.10.0
(function() {
  var Button, Light, Photon, PhotonObject, Room, map, photon;

  map = require('../src/modules/base');

  PhotonObject = map.PhotonObject;

  Room = map.Room;

  Light = map.Light;

  Button = map.Button;

  Photon = require('../src/photon');

  photon = new Photon();

  console.log('# Running script #');

  photon.connect().then(function() {
    console.log('Connected!');
    new Button(null, photon);
    new Light('test', photon);
    PhotonObject.select('test').set('brightness', 100);
    return Button.select().on('pushed', function() {
      PhotonObject.select('test').set('color', 'red');
      return setTimeout(function() {
        return PhotonObject.select('test').set('color', 'blue');
      }, 1000);
    });
  });

}).call(this);
