// Generated by CoffeeScript 1.10.0
(function() {
  var Globals, Util;

  Util = require("./../src/core/util");

  Globals = {};

  Globals['hue'] = 23;

  Util.math.multiply([Globals['hue'], 3]).then(function(response) {
    return console.log(response);
  });

}).call(this);
