// Generated by CoffeeScript 1.10.0
(function() {
  var Button, Light, Objekt, Photon, Room, map, photon;

  map = require('../src/modules/base');

  Objekt = map.Objekt;

  Room = map.Room;

  Light = map.Light;

  Button = map.Button;

  Photon = require('../src/photon');

  photon = new Photon();

  console.log('# Running script #');

  photon.connect().then(function() {
    console.log('Connected!');
    new Light('test1', photon);
    setTimeout(function() {
      Light.get().set('brightness', 100);
      return Light.get().set('color', 'red');
    }, 1000);
    return setInterval(function() {
      return Light.get().set('color', 'random');
    }, 5000);
  });

}).call(this);
