// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, Parts, Scope, error, log, tools;

  tools = require("monky-tools");

  Parts = require("./parts/parts");

  Scope = require("./parts/scope");

  log = tools.console.log;

  error = tools.console.error;

  Parser = (function() {
    function Parser(modules) {
      this.modules = modules;
      this.scope = {
        verb: null,
        object: {
          type: null,
          ref: null
        },
        indirect: {
          "class": null,
          ref: null
        },
        property: null
      };
    }

    Parser.prototype.process = function(line) {
      return line = line.toLowerCase();
    };

    Parser.prototype.parse = function(line) {
      var i, len, ref, result, segments, verb;
      line = this.process(line);
      segments = [];

      /* ADVERB */
      result = Parts.adverb.test(line);
      if (result != null) {
        console.log(result);
        segments.push(result);
      }

      /* VERBS */
      ref = Parts.verbs;
      for (i = 0, len = ref.length; i < len; i++) {
        verb = ref[i];
        result = verb.test(line);
        if (result != null) {
          Scope.type = 'verb';
          Scope.subtype = verb.lexical.base;
          segments.push(result);
        }
      }
      return segments;
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
