// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, Parts, error, log, tools;

  tools = require("monky-tools");

  Parts = require("./parts/parts");

  log = tools.console.log;

  error = tools.console.error;

  Parser = (function() {
    function Parser(modules) {
      this.modules = modules;
      this.scope = {
        verb: null,
        object: {
          type: null,
          ref: null
        },
        indirect: {
          "class": null,
          ref: null
        },
        property: null
      };
    }

    Parser.prototype.process = function(line) {
      return line = line.toLowerCase();
    };

    Parser.prototype.parse = function(line) {
      var result, segments;
      line = this.process(line);
      segments = [];

      /* ADVERB */
      result = Parts.adverb.test(line);
      if (result != null) {
        segments.push(result);
      }

      /* SET */
      result = Parts.set.test(line);
      if (result != null) {
        segments.push(result);
      }
      return segments;
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
