// Generated by CoffeeScript 1.10.0
(function() {
  var Preprocessor, dict;

  dict = require("./dictionaries/dictionary");

  Preprocessor = (function() {
    function Preprocessor() {}

    Preprocessor.numbers = dict.preprocessor.numbers;

    Preprocessor.process = function(line) {
      var i, len, num, ref, word, words;
      ref = this.numbers;
      for (num in ref) {
        words = ref[num];
        for (i = 0, len = words.length; i < len; i++) {
          word = words[i];
          line = line.replace(word, num);
        }
      }
      return line;
    };

    return Preprocessor;

  })();

  module.exports = Preprocessor;

}).call(this);
