class Programmer

  constructor: (map) ->
    @map = map

  capitalize: (string) ->
    string = string[0].toUpperCase() + string[1..]

  indent: (string, level) ->
    level = if level? then level else 0
    indent = Array(level+1).join " "
    string = indent + string

  convertTime: (value, unit) ->

    if unit is 'milliseconds'
      return value

    if unit is 'seconds'
      return value * 1000

    if unit is 'minutes'
      return value * 1000 * 60

    if unit is 'hours'
      return value * 1000 * 60 * 60

    if unit is 'days'
      return value * 1000 * 60 * 60 * 24

  process: (script) ->

    # Empty syntax container
    syntax = []

    indent = 2

    # Loop throught operations in script
    for operation in script

      if operation.type is 'adverbial phrase'

        adverb = operation.adverb

        if adverb is 'delay'

          value = operation.value
          unit = operation.unit

          milliseconds = @convertTime operation.value, operation.unit

          syntax.push "\n\n" + @indent "setTimeout () ->", indent

          indent += 2

          closeAdverbWithValue = milliseconds

        if adverb is 'interval'

          value = operation.value
          unit = operation.unit

          milliseconds = @convertTime operation.value, operation.unit

          syntax.push "\n\n" + @indent "setInterval () ->", indent

          indent += 2

          closeAdverbWithValue = milliseconds

      if operation.type is 'event phrase'

        event = operation.event

        syntax.push "\n" + @indent "photon.on '#{event}', () ->", indent

        indent += 2

        closeEvent = true

      if operation.type is 'verb phrase'

        verb = operation.verb
        ref = operation.object.ref
        # TYPE: Capitalize (for Class name) - TODO: BEAUTIFY!
        type = @capitalize(operation.object.type)
        object = operation.object
        property = operation.property
        # VALUE: If not number -> add quotes
        value = if isNaN operation.value then "'#{operation.value}'" else operation.value

        if verb is 'create'

          # Add autogenerated comment
          syntax.push "\n" + @indent "# Create #{type} called '#{ref}'", indent

          # Add code
          syntax.push @indent "new #{type}('#{ref}', photon)", indent

        if verb is 'set'

          # Add autogenerated comment
          syntax.push "\n" + @indent "# Set the property '#{property}' of '#{ref}' to #{value}", indent

          # Add code
          syntax.push @indent "#{type}.get('#{ref}').set('#{property}', #{value})", indent

        if verb is 'increase'

          # Add autogenerated comment
          syntax.push "\n" + @indent "# Increasing the property '#{property}' of '#{ref}' by #{value}", indent

          # Add code
          syntax.push @indent + "#{type}.get('#{ref}').inc('#{property}', #{value})", indent

        if verb is 'decrease'

          # Add autogenerated comment
          syntax.push "\n" + @indent "# Decreasing the property '#{property}' of '#{ref}' by #{value}", indent

          # Add code
          syntax.push @indent "#{type}.get('#{ref}').dec('#{property}', #{value})", indent

        if verb is 'do'

          # Add autogenerated comment TODO: FIX SO THIS ACTUALLY REFLECTS THE ACTION!
          syntax.push "\n" + @indent "# Blink #{value} times", indent

          # Add code
          syntax.push @indent "#{type}.get('#{ref}').do('blink', #{value})", indent

        if verb is 'log'

          # Add autogenerated comment TODO: FIX SO THIS ACTUALLY REFLECTS THE ACTION!
          syntax.push "\n" + @indent "# Logging", indent

          # Add code
          syntax.push @indent, "console.log #{type}.get('#{ref}')", indent

    if closeAdverbWithValue?
      indent -= 2
      syntax.push "\n" + @indent(", " + closeAdverbWithValue, indent) + "\n"

    if closeEvent?
      indent -= 2

    syntax.join "\n"

  wrap: (code) ->
    output = []
    output.push "map = require './map'"
    output.push "Room = map.Room"
    output.push "Light = map.Light\n"
    output.push "Photon = require './photon'"
    output.push "photon = new Photon()\n"
    output.push "console.log '# Running script #'"

    output.push "photon.connect()\n.then () ->"
    output.push "  console.log 'Connected!'\n"
    output.push code
    # output.push @indent "console.log '# End of script #'", 2
    output.join "\n"

module.exports = Programmer